name: astprinter
description: >
  A command line tool that prints the AST of a dart file.
version: 0.1.0
author: George Kormaris <gekorm@gmail.com>
homepage: https://github.com/GeKorm/astprinter/
dependencies:
  analyzer: ">=0.26.0 <0.27.0"
executables:
  ast:
