name: astprinter
description: >
  A command line tool that prints the AST of a dart file.
version: 0.0.1+1
author: George Kormaris <gekorm@gmail.com>
homepage: https://github.com/GeKorm/astprinter/
dependencies:
  analyzer: any
executables:
  ast:
